apiVersion: v1
kind: Service
metadata:
  name: superhero-generator
spec:
  selector:
    app: superhero-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer